[package]
name = "web-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
shuttle-axum = "0.18.0"
shuttle-runtime = "0.18.0"
tokio = { version = "1.28.2", features = ["full"] }
